MFC r234506:
Fix the following compilation warnings in nxge(4):

  sys/dev/nxge/if_nxge.c:1276:11: error: case value not in enumerated type 'xge_hal_event_e' (aka 'enum xge_hal_event_e') [-Werror,-Wswitch]
            case XGE_LL_EVENT_TRY_XMIT_AGAIN:
                 ^
  sys/dev/nxge/if_nxge.c:1289:11: error: case value not in enumerated type 'xge_hal_event_e' (aka 'enum xge_hal_event_e') [-Werror,-Wswitch]
            case XGE_LL_EVENT_DEVICE_RESETTING:
                 ^

This is because the switch uses xge_queue_item_t::event_type, which is
an enum xge_hal_event_e, while the XGE_LL_EVENT_xx values are of the
enum xge_event_e.

Since messing around with the enum definitions is too disruptive, the
simplest fix is to cast the argument of the switch to int.

Reviewed by:	gnn


Former-commit-id: 5ba2278244c5c37097dc6e0608bfa042089e7b38