Revert r323935 as it broke the build
subr_witness.c:2577:4: error: use of undeclared identifier 'req'
                        req->oldidx = 0;
                        ^


Former-commit-id: c736137d1b7a1a34211145bedf1c22004788c66b