Attempt to make the sound driver recompile, at least for LINT which has the sscape/trix driver active, which (for some reason) disables the mpu401 driver, causing an undefined reference to mpuintr.  This was broken with rev 1.79 (part of the PC98 nss driver commit).
Former-commit-id: 9de7b84332102e04bf6d714b09a171522f92df28