MFC rev. 1.32:
  Work around the fact that nfsclient SRCS must include
  nfs_diskless.c if NFS_ROOT is in effect, e.g., present
  in the kernel config file.  Otherwise the built module
  won't load due to an undefined reference to nfs_setup_diskless.

Approved by:	re (scottl)


Former-commit-id: 0bbef442d0dc7f6ddc04b43dc2ad84a9178872d5