MFC r233354:
Work around the following clang warning in mps(4):

  sys/dev/mps/mps_sas.c:861:1: error: function 'mpssas_discovery_timeout' is not needed and will not be emitted [-Werror,-Wunneeded-internal-declaration]
  mpssas_discovery_timeout(void *data)
  ^

Because the driver is obtained from upstream, we don't want to modify
it; just silence the warning instead, it is harmless.


Former-commit-id: 6f1fdc5116f32d87515bcb46bd011fd5c94c65c3