Work around llvm PR 12623, which makes variables declared with .symver sometimes disappear from the resulting object file, if compiled with clang.  In particular, this can lead to errors when building world with clang and -g, similar to:
  /usr/obj/usr/src/tmp/usr/lib/libc.so: undefined reference to `_malloc_options'

Reported by:	Conrad J. Sabatier <conrads@.no.cox.net>
Reviewed by:	jasone


Former-commit-id: c5ad759b85c3de49afdb2ad67cb910f705b25c25